package syz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollection<M extends BaseCollection<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}

	public java.lang.String getCname() {
		return get("cname");
	}

	public void setZs(java.lang.Integer zs) {
		set("zs", zs);
	}

	public java.lang.Integer getZs() {
		return get("zs");
	}

	public void setDisplay(java.lang.String display) {
		set("display", display);
	}

	public java.lang.String getDisplay() {
		return get("display");
	}

	public void setCollectionPhotoPath(java.lang.String collectionPhotoPath) {
		set("collection_photo_path", collectionPhotoPath);
	}

	public java.lang.String getCollectionPhotoPath() {
		return get("collection_photo_path");
	}

	public void setCollectionCd(java.lang.String collectionCd) {
		set("collection_cd", collectionCd);
	}

	public java.lang.String getCollectionCd() {
		return get("collection_cd");
	}

	public void setCNo(java.lang.String cNo) {
		set("c_no", cNo);
	}

	public java.lang.String getCNo() {
		return get("c_no");
	}

	public void setCWeight(java.lang.String cWeight) {
		set("c_weight", cWeight);
	}

	public java.lang.String getCWeight() {
		return get("c_weight");
	}

	public void setCJs(java.lang.String cJs) {
		set("c_js", cJs);
	}

	public java.lang.String getCJs() {
		return get("c_js");
	}

	public void setCreateMan(java.lang.String createMan) {
		set("create_man", createMan);
	}

	public java.lang.String getCreateMan() {
		return get("create_man");
	}

	public void setUpdateMan(java.lang.String updateMan) {
		set("update_man", updateMan);
	}

	public java.lang.String getUpdateMan() {
		return get("update_man");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
