package syz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMyOrder<M extends BaseMyOrder<M>> extends Model<M> implements IBean {

	public void setOid(java.lang.Integer oid) {
		set("oid", oid);
	}

	public java.lang.Integer getOid() {
		return get("oid");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setOrderDate(java.lang.String orderDate) {
		set("order_date", orderDate);
	}

	public java.lang.String getOrderDate() {
		return get("order_date");
	}

	public void setOrderTime(java.lang.String orderTime) {
		set("order_time", orderTime);
	}

	public java.lang.String getOrderTime() {
		return get("order_time");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCard(java.lang.String card) {
		set("card", card);
	}

	public java.lang.String getCard() {
		return get("card");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
