package syz.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMyInfo<M extends BaseMyInfo<M>> extends Model<M> implements IBean {

	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}

	public java.lang.Integer getMid() {
		return get("mid");
	}

	public void setMsub(java.lang.String msub) {
		set("msub", msub);
	}

	public java.lang.String getMsub() {
		return get("msub");
	}

	public void setPhotoPath(java.lang.String photoPath) {
		set("photo_path", photoPath);
	}

	public java.lang.String getPhotoPath() {
		return get("photo_path");
	}

	public void setPresent(java.lang.String present) {
		set("present", present);
	}

	public java.lang.String getPresent() {
		return get("present");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	public java.lang.String getDetail() {
		return get("detail");
	}

	public void setCreateMan(java.lang.String createMan) {
		set("create_man", createMan);
	}

	public java.lang.String getCreateMan() {
		return get("create_man");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateMan(java.lang.String updateMan) {
		set("update_man", updateMan);
	}

	public java.lang.String getUpdateMan() {
		return get("update_man");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
