package syz.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("collection", "cid", Collection.class);
		arp.addMapping("distribution", "disid", Distribution.class);
		arp.addMapping("message", "meid", Message.class);
		arp.addMapping("my_dh", "did", MyDh.class);
		arp.addMapping("my_info", "mid", MyInfo.class);
		arp.addMapping("my_order", "oid", MyOrder.class);
		arp.addMapping("user", "userid", User.class);
	}
}

