package syz.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import syz.model.base.BaseCollection;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collection extends BaseCollection<Collection> {
	public static final Collection dao = new Collection();

	public Page<Collection> datagrid(int pageNumber, int pageSize, Collection model) {
		List<Object> params = new ArrayList<>();
		String select = "select *";
		String from = "from collection where 1=1";
		if (StrKit.notBlank(model.getCNo())) {
			from += " and c_no like ? ";
			params.add("%" + model.getCNo() + "%");
		}
		if (StrKit.notBlank(model.getCname())) {
			from += " and cname like ? ";
			params.add("%" + model.getCname() + "%");
		}
		if (StrKit.notBlank(model.getCollectionCd())) {
			from += " and collection_cd like ? ";
			params.add("%" + model.getCollectionCd() + "%");
		}
		if (StrKit.notBlank(model.getDisplay())) {
			from += " and display like ? ";
			params.add("%" + model.getDisplay() + "%");
		}
		from += " order by c_no desc";
		return dao.paginate(pageNumber, pageSize, select, from, params.toArray());
	}

}
