package syz.model;

import com.jfinal.plugin.activerecord.Page;
import syz.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message();

	public Page<Message> datagrid(int pageNumber, int pageSize) {
		String select = "select *";
		String from = "from message order by create_time desc";
		return dao.paginate(pageNumber, pageSize, select, from);
	}
}
